### ISSUE TITLE
Compare Perimeter/Area functions

### ISSUE THREAD

**Issue by grantcoz** [B-Minus-Programmers/jojibrush#19] opened 2018-10-26 05:41 UTC
As a user I want to be able to use functions that compare the perimeter/area of a shape

# Tasks: 

-  Create a comparison function that compares the shape perimeter/area

-  The function must be templated

-  Functions are called via a function pointer passed to selection_sort. 

# Tests:

- Error check to verify that the specified shape has a calculable area and perimeter such as lines and polylines

- Verify that the comparison is with the right shape

- Verify that the pointer that is being passed into selection_sort is not being changed unnecessarily 

Priority: High

**Comment by dacruz21** [comment] 2018-10-26 17:59
dupe of #14

**Closed by dacruz21** 2018-10-26 17:59 UTC
